# Generated by Django 3.0.8 on 2020-07-25 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameAttack', models.CharField(max_length=100, verbose_name='Ataque')),
                ('descritionAttack', models.TextField(verbose_name='Sobre')),
                ('featureAttack', models.TextField(verbose_name='Caracteristica')),
            ],
        ),
        migrations.AlterField(
            model_name='produtos',
            name='photo',
            field=models.FileField(upload_to='%Y/%m/%d/'),
        ),
    ]
